apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: psql-0
spec:
  chartRef:
    name: psql-0
    kind: OCIRepository
  interval: 10m
  values:
    fullnameOverride: psql-0
    replicas: 1
    auth:
      username: "admin"
      password: "admin123"
    primary:
      resources:
        requests:
          cpu: 250m
          memory: 250Mi
        limits:
          cpu: 250m
          memory: 250Mi
