apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-demo
spec:
  interval: 10m
  values:
    fullnameOverride: nginx-demo
    replicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 250Mi
      limits:
        cpu: 250m
        memory: 250Mi
    service:
      type: ClusterIP