apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: flux-demo
spec:
  podSelector: {}
  egress:
  - to:
    - ipBlock:
        cidr: ${ip}
    ports:
    - protocol: UDP
      port: 53
  policyTypes:
  - Egress