---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-demo
  namespace: flux-demo
spec:
  interval: 30s
  path: ./clusters/minikube/custom-resources/flux-demo/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
