---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netwokpolicies-flux-demo
  namespace: flux-demo
spec:
  interval: 30s
  path: ./clusters/minikube/custom-resources/flux-demo/networkpolicies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: ip-cm