# include app from custom-source
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networkpolicies-default
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ../../../../components/networkpolicies/default
  prune: true
  wait: true
  timeout: 20m0s